trigger:
  - main
  
pool: ISPPAP20-Agents

steps:
- task: Maven@4
  inputs:
    javaHomeOption: JAVA_HOME_17_X64
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageSourceDirectories: $(System.DefaultWorkingDirectory)/src/main/java/
  displayName: 'Build with Maven'